language: go
sudo: false
go:
  - "1.5"

addons:
  apt:
    packages:
      - 'aspell'
      - 'aspell-en'

install:
  - 'pip install --user linkchecker'
  - 'make clean'
  - 'make themes'
  - 'make travis-server &'
  - 'sleep 10'

script:
  - 'make spellcheck'
  - 'make travis-linkchecker'

notifications:
  email: false
  irc:
    secure: "QTE6uJWybuew3He1jp/pfg2JoF76D7ldoOOwa4y7udyDhOdGasMTxO9ISvx100Jh4F3GRMyJH1QwZJHMmCX5QbDao/Kv2auITOFb6lUtjYW4+gb7WV1vcSdArqyc1ludiGrIAqMyzHUbF5uDuE24qLMiJxgxsjCBNaJ6IML5xNdBgOvJ/xj34vBKGPHVCYNwkmWxfX8xe+3QfG/CAhlDgtFfziW6zYZw6dd9cTH5ecbXkxULNXWgXzr+hsqCyFLp497bTbc+sz/BdY8q7lGzqFQbFE1zYr8Kw7gqFBL4vCalySgyuVu1rtvDY7S5tGjDmUxfjEY/imWeJMHJiyKZlZPiQT3Ay24xXLtvUDQTQS1m6LVeRLzWaW1SLfgqnBayJu4+K8sQmSv57CiF0GxuAWlFTj58AtxLrGg3DrjxJFUkya6uUGdR7sOiSD3TZShQHf/mA/uI3ndqGK6lXmHRFuz8BKLIiezUiDj4WISb6o+RcT+TodFhDLjDTB/I4pcxHSJ3i6oxtZ/f9dh9cJs3OM1Pn4OFq56dCV3lzmZOfjWXbHi/NKY80iX8Qz6MD6lTJHgCb1IaIbqgcID1s7jdN5FfP0DqMripG8RkkeKz9Scapwrn7FOjFXDMXR2SdM2lyknErtrbVygYZcvqC3DUh5fYc0GnM43J8dublZhwbAQ="
