language: 'node_js'
sudo: false
dist: 'trusty'
node_js:
  - "5.12.0"

jdk:
  - 'oraclejdk8'

env:
  global:
    - 'AWS_ACCESS_KEY_ID=AKIAJOOPEXUKZIPG6FIA'
    - secure: "YUWkaDojqjBwpQ/hpappchjqRxzOsJ/mxqIX5E3E+Xt7KiQFQApy6RKZn/Zf+me3ehtyfSJxipHrzkgOjhu8tyWD7Mvu4tBPcQ3xLPPWUj/qcI2xiixzk+mkZuQ8o6iwj/81tnfJtrNc+1/tUVEdlKx7xR2vr3L8j4hG3lYLd9HJ2U01Zs/EmZHFzAsM5Q1jSU1F8HSEGrq1vriN0rV9JO5ompm4lNnC43AXdehvpvkuU1vt7GCFTmgiGpBjZxw3qUcr6qZooKYNwv1vXd+Emok9GwTwrKSVsQjwlLyApDHFxvnRubHt3T1+Mp5PmDIWPZh277CH06gQGRHZ7X0noP6tgT79GGKLkgi1UARmfzSCDww5G39tkOA8us+zcjkueMY+xd+CPtrSBNbexzjN/XW7h1sAa/MNvxZvBfU73IfiX5DhirYjIKU1318UHq5SWh3qo6bevhO1NZpKNvFNmFCYECIZn8TPZOUU+JihnuRRlk5id8FR2wXmOwVKh8QcXA+02HTODaDOeYMpSGB8mRJcDgQa5BRjBzBrmD8AXBdbjO5p4mAzQqIfs/xUsIre2JEQrHVYjz0kTY40ssA/7Ke8GgZ4rIobCh+pheq6DFFbxXrXiPj0LA9p80WNV7aNY3jGCVHnf6Hc/x39dTdIgWBodOxGDPYRZNm/DT42UH8="
    - 'CLOUDFRONT_DISTRIBUTION_ID=E1KIBDKGZ4V1S4'
    - 'GOOGLE_ANALYTICS_ID=UA-70495014-1'
    - 'NOKOGIRI_USE_SYSTEM_LIBRARIES=true'
    - 'GOOGLE_ADSENSE_CLIENT_ID=ca-pub-6377139471527368'
    - 'GOOGLE_ADSENSE_SLOT_ID=1182212332'

before_install:
  - 'git lfs install'
  - 'git lfs pull'
  - 'rvm use 2.3'

install:
  - 'npm install'

script:
  - 'npm run cleanup'
  - 'npm test'

deploy:
  provider: 'script'
  script: 'npm run deploy'
  skip_cleanup: true
  on:
    branch: 'master'
    repo: 'marvinpinto/disjoint.ca'

notifications:
  email: false
  irc:
    secure: "QTE6uJWybuew3He1jp/pfg2JoF76D7ldoOOwa4y7udyDhOdGasMTxO9ISvx100Jh4F3GRMyJH1QwZJHMmCX5QbDao/Kv2auITOFb6lUtjYW4+gb7WV1vcSdArqyc1ludiGrIAqMyzHUbF5uDuE24qLMiJxgxsjCBNaJ6IML5xNdBgOvJ/xj34vBKGPHVCYNwkmWxfX8xe+3QfG/CAhlDgtFfziW6zYZw6dd9cTH5ecbXkxULNXWgXzr+hsqCyFLp497bTbc+sz/BdY8q7lGzqFQbFE1zYr8Kw7gqFBL4vCalySgyuVu1rtvDY7S5tGjDmUxfjEY/imWeJMHJiyKZlZPiQT3Ay24xXLtvUDQTQS1m6LVeRLzWaW1SLfgqnBayJu4+K8sQmSv57CiF0GxuAWlFTj58AtxLrGg3DrjxJFUkya6uUGdR7sOiSD3TZShQHf/mA/uI3ndqGK6lXmHRFuz8BKLIiezUiDj4WISb6o+RcT+TodFhDLjDTB/I4pcxHSJ3i6oxtZ/f9dh9cJs3OM1Pn4OFq56dCV3lzmZOfjWXbHi/NKY80iX8Qz6MD6lTJHgCb1IaIbqgcID1s7jdN5FfP0DqMripG8RkkeKz9Scapwrn7FOjFXDMXR2SdM2lyknErtrbVygYZcvqC3DUh5fYc0GnM43J8dublZhwbAQ="
