language: 'node_js'
sudo: false
dist: 'trusty'
node_js:
  - '6.11.2'

jdk:
  - 'oraclejdk8'

cache:
  yarn: true
  directories:
    - 'node_modules'
    - '$HOME/bin'

env:
  global:
    - 'AWS_ACCESS_KEY_ID=AKIAJOOPEXUKZIPG6FIA'
    - secure: "YUWkaDojqjBwpQ/hpappchjqRxzOsJ/mxqIX5E3E+Xt7KiQFQApy6RKZn/Zf+me3ehtyfSJxipHrzkgOjhu8tyWD7Mvu4tBPcQ3xLPPWUj/qcI2xiixzk+mkZuQ8o6iwj/81tnfJtrNc+1/tUVEdlKx7xR2vr3L8j4hG3lYLd9HJ2U01Zs/EmZHFzAsM5Q1jSU1F8HSEGrq1vriN0rV9JO5ompm4lNnC43AXdehvpvkuU1vt7GCFTmgiGpBjZxw3qUcr6qZooKYNwv1vXd+Emok9GwTwrKSVsQjwlLyApDHFxvnRubHt3T1+Mp5PmDIWPZh277CH06gQGRHZ7X0noP6tgT79GGKLkgi1UARmfzSCDww5G39tkOA8us+zcjkueMY+xd+CPtrSBNbexzjN/XW7h1sAa/MNvxZvBfU73IfiX5DhirYjIKU1318UHq5SWh3qo6bevhO1NZpKNvFNmFCYECIZn8TPZOUU+JihnuRRlk5id8FR2wXmOwVKh8QcXA+02HTODaDOeYMpSGB8mRJcDgQa5BRjBzBrmD8AXBdbjO5p4mAzQqIfs/xUsIre2JEQrHVYjz0kTY40ssA/7Ke8GgZ4rIobCh+pheq6DFFbxXrXiPj0LA9p80WNV7aNY3jGCVHnf6Hc/x39dTdIgWBodOxGDPYRZNm/DT42UH8="
    - 'CLOUDFRONT_DISTRIBUTION_ID=E1KIBDKGZ4V1S4'
    - 'GOOGLE_ANALYTICS_ID=UA-70495014-1'
    - 'NOKOGIRI_USE_SYSTEM_LIBRARIES=true'

before_install:
  - 'git lfs install'
  - 'git lfs pull'
  - 'rvm use 2.3'

install:
  - 'yarn install'
  - 'yarn add --force node-sass'

before_script:
  - 'unset JAVA_TOOL_OPTIONS && unset _JAVA_OPTIONS'

script:
  - 'yarn run cleanup'
  - 'yarn test'

deploy:
  provider: 'script'
  script: 'yarn run deploy'
  skip_cleanup: true
  on:
    branch: 'master'
    repo: 'marvinpinto/disjoint.ca'

notifications:
  email: false
  webhooks:
    urls:
      - secure: "rJsX/QMAeRfzRxMZxi0kb28K4lgZX1APG0+J2hr61MS/3yjMIK6DNBkORg7kHYzRKCdL/RmlMgimMQCPsV5RHZiczm35reISG/EskBqyIo+owz16KCDTOdO+90SoG83QbfnDNBAgHTZYK06ujbySpGcYXHWWp03mpP93D3XpI+gaY8qBvj0ajttlyoiBXO1KcD4RIMhDbOMs4DttVjYvdwwJqP3yJ/in78HdUnLMwYK7dQr9l441+Aro3/ME6a3BU9f3o2cLLI+b8zQqATvx4D6t2iZtGpkezyXdaoQOGmZUOPzziLTdAIyEO8VUcnPwLI0cjnBkQbc/AmDvScds/giCkAW8brSjscmubNwH3ryfOn/Dao5gjv1UcCaCxLaA5NeJ7VDTOXG5Kn3DxVRQSVYedZjUx1O1dZ3Tc8JTO3kM5KJVIVZZlDV8Ka+c1eGXeD8i+Ep2yIW3mwFufbF6Z93LwnpHZv2azzBh0Y+Hv+o3iyEVuoPdHWmCnpQbXILWnPA2R3h3m1479RxYpWh4oFevAgWzzwk2slI2kLt1DuvOPOkf5XAcj4NAYzdJ+8hI9hrkZbcUdGVbiZIl0xAFPj+oXuuh9d2sR+qhEXuoPIbsPtcDLqsR6VF87exzgMBFFW83QwcbP6I6kTX2+F9lHTHunWUSGMyQIUYZviFyGDk="
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
