---
baseurl: "https://disjoint.ca"
title: "disjoint.ca"
paginate: 10
MetaDataFormat: "yaml"
theme: "hugo-multi-bootswatch"
languageCode: "en-us"

author:
  name: "Marvin Pinto"
  email: "marvin@pinto.im"

permalinks:
  writing: "/writing/:year/:month/:day/:title/"
  til: "/til/:year/:month/:day/:title/"

taxonomies:
  tag: "tags"

#
# All parameters below here are optional and can be mixed and matched.
#
params:
  # language code for the website
  languageCode: "en-us"

  # name of the site author; used in header meta information
  author: "Marvin Pinto"

  # social links, used in footer, these must be full URLs.
  github: "https://github.com/marvinpinto"
  twitter: "https://twitter.com/marvinpinto"
  # linkedin: ""

  # show default summaries on the frontpage or not
  use_summaries: false

  theme:
    inverse: false
    name: "lumen"

  # naming of the elements in your blog/site
  strings:

    # used date format
    date_format: "Jan 2, 2006"
